deinsoftware/fun-with-flags

.github/workflows/codeql.yml, .github/workflows/dependency-review.yml, .github/workflows/sonarcloud.yml, .vscode/settings.json
=> added github actions workflows

package.json
Add stylelint command scripts
Show errors:
`npm run styles`
Try to fix automagically the errors:
`npm run styles:fix`
=> Git config

.github/workflows/sonarcloud.yml
Trying to fix the sonar configuration
=> Project config

src/app/api/timezones/route.ts, src/helpers/dates.test.ts, src/helpers/events.test.ts
=> Fix code smells

package-lock.json, package.json, src/app/components/list-of-coutries/ListOfCountries.module.css, src/app/components/list-of-coutries/ListOfCountries.tsx, src/app/components/list-of-coutries/useFetch.js, src/app/components/list-of-coutries/useFetch.tsx, src/app/list-countries/page.tsx
=> Flag Dependecy, Fetching API, ListOfCountries component [demo] 

src/app/components/ComboboxCountries/ComboboxCountries.tsx, src/app/components/ComboboxCountries/useFilteredDates.ts, src/app/components/ComboboxCountries/useGetNextAndPrevDay.ts, src/app/components/ComboboxCountries/useNextAndPrevDay.ts, src/app/context/timeZoneContext.tsx, src/app/layout.tsx, src/types/DateArray.types.ts
Create context to flag timezones.
=> Share events

.github/workflows/build.yml, src/helpers/dates.test.ts, src/helpers/dates.ts
=> Refactor helpers

src/app/components/atoms/ui/button/Button.module.css, src/app/components/atoms/ui/button/Button.tsx
=> fix login button

src/app/components/atoms/util/toggle/Toggle.module.css, src/app/components/molecules/country-list/CountryList.module.css, src/app/components/organisms/events/CreateEvent.module.css, src/app/components/organisms/events/CreateEvent.tsx
True/Active 👉🏽 Right
False/Disabled 👈🏽 Left
https://www.behance.net/gallery/70302039/History-Of-Toggle-UIUX-Case-Study-UI-Samples
=> CreateEvent visual bugs 🐱‍🏍

src/app/components/atoms/util/hashtags-input/HashtagsInput.module.css, src/app/components/atoms/util/hashtags-input/HashtagsInput.tsx, src/app/components/atoms/util/toggle/Toggle.module.css, src/app/components/molecules/country-list/CountryList.module.css, src/app/components/organisms/events/CreateEvent.module.css, src/app/components/organisms/events/CreateEvent.tsx, src/app/components/organisms/events/CreateEvent.types.ts, src/app/components/organisms/events/useGetFormData.ts
=> HashtagsInput 🐱‍👤 (Component)

src/app/components/atoms/country-combo/DatesToRender.module.css, src/app/components/atoms/country-combo/DatesToRender.tsx, src/app/components/atoms/ui/button/Button.tsx, src/app/components/atoms/util/time-picker/TimePicker.tsx, src/app/components/molecules/country-combo/ComboboxCountries.tsx, src/app/components/molecules/select-country/SelectCountry.module.css, src/app/components/molecules/select-country/SelectCountry.tsx, src/app/components/organisms/events/CreateEvent.module.css, src/app/components/organisms/events/CreateEvent.tsx, src/app/context/timeZoneContext.tsx
- Integrate format
- fix Combo placeholder
- add useCallback to context
- add debounce to TimePicker
- remove time-zones on create event
- add controllers to Combo
=> Integrate format

src/app/components/molecules/select-country/SelectCountry.tsx, src/app/components/organisms/events/CreateEvent.tsx
Make independent SelectCountry component
=> refactor SelectCountry

src/app/api/timezones/route.ts, src/app/components/organisms/events/useGetFormData.ts, src/helpers/dates.test.ts, src/helpers/dates.ts, src/helpers/events.ts, src/helpers/get-time-zone.ts, src/helpers/locale.test.ts, src/helpers/locale.ts, src/helpers/timezones.test.ts, src/helpers/timezones.ts
=> Fix default location

src/app/components/atoms/country-combo/DatesToRender.module.css, src/app/components/atoms/util/toggle/Toggle.tsx, src/app/components/molecules/country-combo/ComboboxCountries.module.css, src/app/components/molecules/country-combo/ComboboxCountries.tsx, src/app/components/molecules/select-country/SelectCountry.module.css, src/app/components/molecules/select-country/SelectCountry.tsx, src/app/components/organisms/events/CreateEvent.module.css, src/app/components/organisms/events/CreateEvent.tsx
Before:
After 0.2rem:
Before:
After 0.14rem:
=> fixed some visual bugs

src/app/components/organisms/events/CreateEvent.tsx
=> Validation before save

src/app/components/atoms/util/hashtags-input/HashtagsInput.module.css, src/app/components/atoms/util/hashtags-input/HashtagsInput.tsx, src/app/components/atoms/util/toggle/Toggle.module.css, src/libs/icon-config.ts
=> Refactor(app): HasgTagsInput (Component) / Functions + Styles

src/app/[locale]/components/molecules/country-combo/ComboboxCountries.module.css, src/app/[locale]/components/molecules/country-combo/ComboboxCountries.tsx, src/app/[locale]/components/molecules/country-list/CountryList.module.css, src/app/[locale]/components/molecules/country-list/CountryList.tsx
Standarized Combobox placeholder and added lens in CountryList
[100%]
=> Refactor(app): fixed visual bugs in Combobox and added LensIcon in CountryList

src/app/[locale]/components/organisms/events/CreateEvent.tsx, src/app/[locale]/layout.tsx, src/messages/en.json, src/messages/es.json
- why? 
- It's necessary to give feedback when a button is clicked on a mobile
- https://pickaso.com/2021/7-consejos-disenar-botones-ux-ui#7_Estados_y_feedback
- https://slashmobility.com/blog/2023/04/6-errores-garrafales-al-disenar-un-boton/ (error 6)
- _but it's not working yet_
=> feat(app): Added toast when TimeZone is already selected

src/app/[locale]/components/molecules/select-country/SelectCountry.module.css, src/app/[locale]/components/molecules/select-country/SelectCountry.tsx
=> feat(app): Added icon on selectCountry

src/app/[locale]/components/organisms/events/CreateEvent.module.css
=> Mrredu/fix/Double icon in Date input

src/app/[locale]/components/atoms/auth/LoginButton.tsx, src/app/[locale]/layout.tsx
=> fix(app): Added translation in LoginButton

src/app/[locale]/components/organisms/login/Login.jsx, src/app/[locale]/components/organisms/login/Login.module.css, src/app/[locale]/login/page.tsx, src/messages/en.json, src/messages/es.json
=> feat(app): Added i18n in LoginPage

src/app/[locale]/components/organisms/events/CreateEvent.module.css, src/app/[locale]/components/organisms/events/CreateEvent.tsx
=> fix(app): padding in combobox's toggle

src/app/[locale]/components/atoms/util/toast-alert-message/ToastAlertMessage.tsx, src/app/[locale]/components/molecules/hashtags/Hashtags.module.css, src/app/[locale]/components/molecules/select-country/SelectCountry.module.css, src/styles/globals.css
=> feat(app): toast alert message

src/messages/es.json
fix notice text structure in Spanish dictionary
=> fix(app): :ambulance: i18n notice text

src/app/[locale]/components/atoms/country-combo/DatesToRender.tsx, src/app/[locale]/components/molecules/country-combo/ComboboxCountries.tsx, src/app/[locale]/components/organisms/events/CreateEvent.module.css, src/app/[locale]/components/organisms/events/CreateEvent.tsx, src/app/[locale]/components/organisms/events/useShareEvent.ts, src/messages/en.json, src/messages/es.json
Disabled emojis:
Enabled emojis:
=> feat(app): format event message with emojis

src/app/[locale]/components/organisms/events/CreateEvent.tsx
=> feat(app): changed twitter icon

src/app/[locale]/components/atoms/auth/LoginButton.tsx, src/app/[locale]/components/atoms/util/SearchBar.module.css, src/app/[locale]/components/atoms/util/SearchBar.tsx, src/app/[locale]/components/atoms/util/time-picker/TimePicker.module.css, src/app/[locale]/page.module.css
=> Bug decline cookies 👁‍🗨
